### ISSUE TITLE
With transpiled files, the following error comes while deploying: File contains different line feeds. Mixed line feeds are not supported

### ISSUE THREAD

**Issue by arindamseth** [petermuessig/ui5-ecosystem-showcase#115]
With transpiled files, the following error comes while deploying: 
"File contains different line feeds. Mixed line feeds are not supported"
Is it possible to follow existing EOL characters while transpiling?

**Comment by vobu** [comment]
hi, hm, not sure, never had this case. would you mind switching to unix-stlye line feeds (`lf`) and converting the files in question to that linefeed-style?

**Comment by arindamseth** [comment]
Yes, as a measure to use this, I have switched to LF instead of CRLF. However I was wondering if it was possible for this tool to follow existing EOL characters. Thanks

**Comment by vobu** [comment]
don't see this (mixed line feeds) being done - I'd rather use a .editorrc or .prettierrc forcing `lf` linefeeds :)

**Comment by lboehm** [comment]
Just my two cents :) I had the same problem, and first I forced my editor (on windows) to use unix style linefeeds. But I was not satisfied with this approach (I don't remember why 🤦‍♂), so I now modify linefeed when transpiling:

````
var correctLinefeed = result.code.replace(/\r\n|\r|\n/g, '\r\n');
resource.setString(correctLinefeed);
workspace.write(resource);
````
(*This snippet has to be put in promises `then` in [transpile module](https://github.com/petermuessig/ui5-ecosystem-showcase/blob/master/packages/ui5-task-transpile/lib/transpile.js)*)

This code changes the linefeed to `\r\n`, it would be better to check which OS is used and set the linefeed based on the OS. But as we all are using Windows this works fine for us.

HTH

**Comment by vobu** [comment]
cool, would you put this in a PR?

**Comment by lboehm** [comment]
Okay, I'll give it a try :)
