### ISSUE TITLE
Livereload does not work on Microsoft Edge (chromium)

### ISSUE THREAD

**Issue by bniculea** [petermuessig/ui5-ecosystem-showcase#116]
I have configured the application to use the ui5-middleware-livereload (^0.1.4) and  the refresh is working on Chrome but not on Microsoft Edge, even though they share the same platform. 
It might be a hard dependency on Chrome and not Chromium.

**Comment by vobu** [comment]
i'll check while upgrading deps soon

**Comment by vobu** [comment]
just tested this with the latest `edge` (macOS) -> works!
might be due to a recent version bump of the underlying `livereload` module.
please re-test and either close on resolve (hopefully :) ) or describe any potential (new) problems.
thx!

**Comment by bniculea** [comment]
Great!
It works now, Edge has done some update too. 
Nevertheless, thank you!
