### ISSUE TITLE
build fails for @sap\node-jwt

### ISSUE THREAD

**Issue by arcanist123** [petermuessig/ui5-ecosystem-showcase#125]
Hello.

I am somehow not able to follow the readmy without getting the error. I have node 12.XX
I am doing the following:
git clone https://github.com/petermuessig/ui5-ecosystem-showcase
cd ui5-ecosystem-showcase
yarn --ignore-engines

And getting the attached error. 
[issue_yarn.txt](https://github.com/petermuessig/ui5-ecosystem-showcase/files/4208593/issue_yarn.txt)

**Comment by vobu** [comment]
fs-events and node-gyp are always special candidates that tend to work with LTS node versions only. so please get node 12 LTS and try again.

**Comment by arcanist123** [comment]
I have Node version v12.16.0 which is LTS

**Comment by petermuessig** [comment]
I upgraded the dependencies and the yarn.lock file now. Maybe this helps to solve the issue as node-jwt has been upgraded to 1.6.6 now.

**Comment by arcanist123** [comment]
same error 

C:\Users\Arcanist\IdeaProjects\ui5-ecosystem-showcase>yarn --ignore-engines
yarn install v1.22.0
[1/5] Resolving packages...
[2/5] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/5] Linking dependencies...
[4/5] Building fresh packages...
[-/2] ⠈ waiting...                                                                                                      error C:\Users\Arcanist\IdeaProjects\ui5-ecosystem-showcase\node_modules\@sap\node-jwt: Command failed.
Exit code: 1
Command: node ./build.js
Arguments:
Directory: C:\Users\Arcanist\IdeaProjects\ui5-ecosystem-showcase\node_modules\@sap\node-jwt
Output:
Build failed
