### ISSUE TITLE
General configuration from environment variables and .env files

### ISSUE THREAD

**Issue by esjewett** [petermuessig/ui5-ecosystem-showcase#174]
It would help a lot for CI scenarios if settings could optionally be pulled from environment variables. Support for dot-env on top of this would be fantastic. I'm mostly interested in this for ui5-middleware-simpleproxy in order to set the `baseUri`, but seems like something that would be a good standard for all tasks and middleware. Thoughts? Would pull requests to implement this be accepted in theory?

**Comment by vobu** [comment]
absolutely. dotenv rocks 👍🏻

**Comment by petermuessig** [comment]
@esjewett - yes, pull requests will be appreciated! :-)

**Comment by petermuessig** [comment]
PR #180 submitted - thanks for your contribution... :-)
