### ISSUE TITLE
Dynamic port for ui5-middleware-livereload

### ISSUE THREAD

**Issue by resitamas** [petermuessig/ui5-ecosystem-showcase#187]
I develop several applications and use the _ui5-middleware-livereload_. I very often encounter the problem that I am not able to start an application because the port which I set for the _livereload_ server is already used by another application's _livereload_ server. I know that it is possible to set different ports, but for that I have to remember which ports have already been taken. It think this is not really flexible.

What do you think about a feature that in case this port is not set explicitly then it is set automatically to one which is not yet used?

**Comment by vobu** [comment]
automatically setting a non-taken port if none is supplied via configuration is a good idea!
so in https://github.com/petermuessig/ui5-ecosystem-showcase/blob/24afc7e178084e2994e63a7f456e2855bb78d362/packages/ui5-middleware-livereload/lib/livereload.js#L23, if `options.configuration.port` is supplied, it would take precedence. 
if not supplied, [get-port](https://www.npmjs.com/package/get-port) or similar could be used for selecting an open port.
go for it 💪 !

**Comment by petermuessig** [comment]
I submitted the pr #195 right now - big thanks for the contribution
