### ISSUE TITLE
ui5-middleware-simpleproxy: module dotenv not found

### ISSUE THREAD

**Issue by resitamas** [petermuessig/ui5-ecosystem-showcase#197]
After upgrading to **0.2.2** of _ui5-middleware-simpleproxy_ it gives me the error when trying to run the `ui5 serve` command:

"middlewareRepository: Failed to require middleware module for ui5-middleware-simpleproxy: Cannot find module 'dotenv'"

I also checked my _node-modules_ folder after `npm install` and couldn't find the folder _dotenv_.

**Comment by petermuessig** [comment]
Fixed with **0.2.3** of _ui5-middleware-simpleproxy_ - thanks for reporting

Fixed with: https://github.com/petermuessig/ui5-ecosystem-showcase/commit/77d436004d187cb696f98cc0d742ee1ad2a75b0e
