### ISSUE TITLE
place each middleware/task in one repo

### ISSUE THREAD

**Issue by bkrrrr** [petermuessig/ui5-ecosystem-showcase#22]
As seen [here](https://github.com/npm/npm/issues/2974)  
`npm install https://github.com/{USER}/{REPO}/tarball/{BRANCH}`
doesn't work for monorepos. 

This makes forking and adjusting really pointless, i can`t install my own extension in a persistent way into my project. 

real live example: 
`npm install https://github.com/bkrrrr/ui5-ecosystem-showcase/ui5-middleware-livereload `

**Comment by vobu** [comment]
hi, why not do 
`npm install ui5-middleware-livereload --save-dev` 
in your project?
all the custom middlwares and tasks are available as standalone npm modules.

**Comment by bkrrrr** [comment]
because i made some changes & im not interested in making a npm ui5-middleware-livereload2...
 
I just pointed out, that this is bad practice because of the former mentioned reasons and not supported by npm.

**Comment by petermuessig** [comment]
Hi @bkrrrr ,

you can also use linking to connect two NPM projects locally. Sync the repo locally, like the livereload middleware with your project and modify it.

BR,
Peter
