### ISSUE TITLE
ui5-task-transpile - custom babel configuration

### ISSUE THREAD

**Issue by lennart-m** [petermuessig/ui5-ecosystem-showcase#246]
Hi, I think it would help a lot to make the babel configuration used by the task configurable.
The configuration could be done in `ui5.yaml` and at runtime be merged with some defaults already implemented and then passed into babel:
https://github.com/petermuessig/ui5-ecosystem-showcase/blob/master/packages/ui5-task-transpile/lib/transpile.js#L29

Motivation: for some projects some assumptions about the code can be made and those make the transpiled files be smaller in size and more readable, e.g. [@babel/plugin-transform-for-of](https://babeljs.io/docs/en/babel-plugin-transform-for-of#assumearray) with option `assumeArray` set to `true`.

**Comment by lennart-m** [comment]
OK I'm really sorry. I thought I tried everything but it seems like a file `babel.config.json` is picked up by the task automatically already. I guess this makes my suggestion irrelevant.
It also works for `ui5-middleware-livetranspile`.

**Comment by vobu** [comment]
cool 😎
how about documenting the config option via a babel-file in the task’s and middleware’s `README.md` in a PR? (hint hint 😄)

**Comment by lennart-m** [comment]
I was a little bit too fast again. Only checked with `Component.js` and it seems that file is treated differently from the rest.
So for `Component.js` the babel.config.json` is read but for controllers it isn't.

I will do some more testing later on. Reopening the issue as the functionality is not yet available for other files.

**Comment by lennart-m** [comment]
Again I have to reject my previous statement 🤨

I have no idea what I did the last time but it seems to function as stated in my [first comment](https://github.com/petermuessig/ui5-ecosystem-showcase/issues/246#issuecomment-652659092). Sorry for this mess.

In fact it suffices to add the file `babel.config.json` in order to extend the babel configuration. I successfully implemented this in several projects now. It's such a joy to finally be able to `async`/`await` 🥳

I created PR #265 that adds the documentation, as suggested by @vobu 

But there is another possible approach: I created PR #266 that implements an option `babelConfig` in `ui5.yaml` that can be used to completely override the babel configuration.
That PR also modifies the `ui5-app`, I'm starting to think it might be better to not include those changes. Is it possible for you to only approve the changes in `ui5-task-transpile` and `ui5-middleware-livereload`?

**Comment by Shingaz** [comment]
@lennart-m It does not work on my side. Before I was compiling everything with Babel into `webapp` before serving it and if I keep the same Babel config (`.babelrc.js` or `babel.config.json`) at the root of the project I got compilation errors.

My livetranspile config:
```
server:
  customMiddleware:
    - name: ui5-middleware-livetranspile
      afterMiddleware: compression
      configuration:
        debug: true
        filePattern: '.{js,ts}'
```
