### ISSUE TITLE
Unable to install live-reload middleware

### ISSUE THREAD

**Issue by dracovoldy** [petermuessig/ui5-ecosystem-showcase#279]
Fails to install live-reload middleware on Ubuntu 18.04 npm@6.14.5, node@v12.18.2

npm WARN tarball tarball data for @sap/node-jwt@1.6.11 (sha512-Wr3ARQWQAWoZqVF3fM/s1z+B5n9Ne+4l/BBncb8OckwYB3P6t3aV0CjaA35dcLo4vLG8aT/Lf+E7c0Lga3e6KQ==) seems to be corrupted. Trying one more time.

**Comment by vobu** [comment]
sounds more like a repo/local node issue to me. 
try
- reinstalling your modules in your proj: rm -rf node_modules && yarn 
- checking what repo you use, either in your proj's .npmrc or in the global ~/.npmrc

**Comment by petermuessig** [comment]
Please also delete the `yarn.lock` if the issue still persists - I will update the yarn.lock today - maybe this issue is related to moving the @sap dependencies from npm.sap.com to npmjs.com

**Comment by vobu** [comment]
closing this as there was no reaction from the original author > 4 weeks
