### ISSUE TITLE
Simple proxy adds an ETag, "normal" service does not - concurrency error

### ISSUE THREAD

**Issue by jorgt** [petermuessig/ui5-ecosystem-showcase#292]
Hi Peter, 

Using the simple proxy after separating UI and Backend results in some cases in a repeated error on the odata services (this was with the V2 adapter)
```
<message>The requested resource is not concurrent</message>
```

I think I tracked it down to the addition of an ETag on the request, and the responding `if-none-matched` header on subsequent calls. The below GIF is a bit crap but the only difference is the ETag and the subsequent `if-none-matched` response. 

My solution was to add a `delete proxyReqOpts.headers['if-none-match'];` to function `proxyReqOptDecorator` but that's only because I had no better way of trying to remove the ETAg. The original request to the CAP service itself does not generate an ETag at all. I did not find a way to succesfully set `app.set('etag', false)`. 

![error](https://user-images.githubusercontent.com/2444503/91831708-bfc01c80-ec87-11ea-88b2-90ca3d9e9c2f.gif)

**Comment by petermuessig** [comment]
Hi @jorgt ,

I will take a look into this issue the next days... Thanks for your suggestion... :-)

BR,
Peter

**Comment by bkrrrr** [comment]
I think I came across the same problem with cap(OData v4) while upgrading 2.3 -> 4.1.
Something happens to the payload while proxying and the ui5 requestor can't parse it afterward anymore.

The error is pointing to etag

``
Uncaught TypeError: Cannot create property '@odata.etag' on string '--batch_id-`
``
![image](https://user-images.githubusercontent.com/14314310/94257991-7a140e00-ff2c-11ea-8111-1a2a3d142c36.png)

For everyone facing this problem downgrading to 2.3 works

**Comment by petermuessig** [comment]
Hi @bkrrrr ,

could this be related to https://github.com/petermuessig/ui5-ecosystem-showcase/issues/293 - the limit is quite low by default. I am about to add a parameter to increase the payload by configuration.

Cheers,
Peter

**Comment by petermuessig** [comment]
Hi @jorg ,

a similar issue had been reported to the `express-http-proxy` and the workaround there was also to remove the `etag` from the response: https://github.com/villadora/express-http-proxy/pull/463 - but I will research a bit more...

BR, Peter

**Comment by petermuessig** [comment]
@jorgt - the PR removes the ETag from the response - maybe this is better but even hacky than your suggestion above.
