### ISSUE TITLE
ui5-task-flatten-library not on NPM

### ISSUE THREAD

**Issue by chrismills** [petermuessig/ui5-ecosystem-showcase#309]
Hi There,

Was keen to checkout the ui5-task-flatten-library but looks like its not on npm? The link provided in the project documentation leads to a 404 (https://www.npmjs.com/package/ui5-task-flatten-library)

Thanks

Chris

**Comment by vobu** [comment]
yep, that's right, @petermuessig is behind schedule 😂

**Comment by petermuessig** [comment]
Grml - just back from vacation - I promise a delivery for today evening... 😢

**Comment by chrismills** [comment]
Oh no stress @petermuessig whenever is fine. Thanks :)

**Comment by petermuessig** [comment]
The module is now on NPM with version 0.2.0: https://www.npmjs.com/package/ui5-task-flatten-library
