### ISSUE TITLE
ui5-task-stringreplacer: Cannot find module 'lodash.escaperegexp'

### ISSUE THREAD

**Issue by nbmedikonda** [petermuessig/ui5-ecosystem-showcase#337]
taskRepository: Failed to require task module for ui5-task-stringreplacer: Cannot find module 'lodash.escaperegexp'

**Comment by vobu** [comment]
way too few information so that we could help w/ anything.
if still relevant, please list
- your env, incl OS + Node.js version
- ui5.yaml

**Comment by nbmedikonda** [comment]
@vobu - i can see this in 0.5.1.it was added by peter today morning
