### ISSUE TITLE
Simpleproxy: Configuration of url parameters

### ISSUE THREAD

**Issue by marcelschork** [petermuessig/ui5-ecosystem-showcase#428]
For sending OData requests to SAP Netweaver multi client systems the url parameter "sap-client" needs to be specified, e.g.

`https://my.sap.system/sap/opu/odata/sap/z_sample_service/$metadata?sap-client=206`

By now it's not possible to configure url parameters via the configuration object. Therefore development and testing on multi client systems is not really convenient.

My suggestion is to extend the configuration by a map named "query" which allows to specify url parameters as key-value pairs. 

I already implemented it and could provide this feature via a PR.

**Comment by vobu** [comment]
proxied url params via the config in ui5.yaml sound good to me!
-> PR most welcome!

**Comment by petermuessig** [comment]
Fixed with #440

**Comment by petermuessig** [comment]
Great contribution! 👍
